menus = [
  { "id" => 3, "title" => "Меню в шапке", "descriptor" => "in_head" },
  { "id" => 4, "title" => "Меню в футоре", "descriptor" => "in_footer_primary" },
  { "id" => 5, "title" => "Меню в футоре дополнительное", "descriptor" => "in_footer_secondary" }
]
Menu.create(menus) if Menu.count.zero?

menu_items = [
  { "id" => 7, "menu_id" => 4, "title_ru" => "О нас", "title_en" => "About us", "link_ru" => "/pages/14", "link_en" => "/pages/14", "position" => 1 },
  { "id" => 13, "menu_id" => 5, "title_ru" => "Политика конфединциальности", "title_en" => "Privacy policy", "link_ru" => "/pages/16", "link_en" => "/pages/16", "position" => 2 },
  { "id" => 10, "menu_id" => 4, "title_ru" => "Новости и блоги", "title_en" => "News and blogs", "link_ru" => "/blog/", "link_en" => "/blog", "position" => 4 },
  { "id" => 3, "menu_id" => 3, "title_ru" => "Страны", "title_en" => "Countries", "link_ru" => "/countries", "link_en" => "/countries", "position" => 1 },
  { "id" => 6, "menu_id" => 3, "title_ru" => "О нас", "title_en" => "About us", "link_ru" => "/pages/14", "link_en" => "/pages/14", "position" => 4 },
  { "id" => 2, "menu_id" => 3, "title_ru" => "Туры", "title_en" => "Tours", "link_ru" => "/tours", "link_en" => "/tours", "position" => 2 },
  { "id" => 8, "menu_id" => 3, "title_ru" => "Новости и блоги", "title_en" => "News and blogs", "link_ru" => "/blog/", "link_en" => "/blog", "position" => 3 },
  { "id" => 14, "menu_id" => 3, "title_ru" => "Вход в аккаунт гида", "title_en" => "Guide account", "link_ru" => "/guides/sign_in", "link_en" => "/guides/sign_in", "position" => 5 },
  { "id" => 30, "menu_id" => 4, "title_ru" => "Условия пользования", "title_en" => "Terms of use", "link_ru" => "/pages/15", "link_en" => "/pages/15", "position" => 3 },
  { "id" => 31, "menu_id" => 4, "title_ru" => "Политика конфединциальности", "title_en" => "Privacy policy", "link_ru" => "/pages/16", "link_en" => "/pages/16", "position" => 4 }
]
MenuItem.create(menu_items) if MenuItem.count.zero?

languages = [
  { "id" => 1, "title_ru" => "Русский", "title_en" => "Russian" },
  { "id" => 2, "title_ru" => "Английский", "title_en" => "English" },
  { "id" => 3, "title_ru" => "Испанский", "title_en" => "Spanish" },
  { "id" => 4, "title_ru" => "Портуагальский", "title_en" => "Portuguese" },
  { "id" => 5, "title_ru" => "Китайский", "title_en" => "Chinese" },
  { "id" => 6, "title_ru" => "Японский", "title_en" => "Japanese" }
]
Language.create(languages) if Language.count.zero?

tour_types = [
  {
    "id" => 10,
    "title_ru" => "Снег",
    "title_en" => "Snow",
    "description_ru" => "",
    "description_en" => "",
    "avatar" => "public/uploads/tour_type/avatar/10/voshogdenie1.jpg",
    "large_avatar" => "public/uploads/tour_type/large_avatar/10/snow.jpg",
    "slug_ru" => "",
    "slug_en" => "",
    "meta_title_ru" => "",
    "meta_title_en" => "",
    "meta_description_ru" => "",
    "meta_description_en" => "",
    "meta_keywords_ru" => "",
    "meta_keywords_en" => ""
  },
  {
    "id" => 13,
    "title_ru" => "Вело",
    "title_en" => "Bicycle",
    "description_ru" => "",
    "description_en" => "",
    "avatar" => "public/uploads/tour_type/avatar/13/cycling1.jpg",
    "large_avatar" => "public/uploads/tour_type/large_avatar/13/velo.jpg",
    "slug_ru" => "",
    "slug_en" => "",
    "meta_title_ru" => "",
    "meta_title_en" => "",
    "meta_description_ru" => "",
    "meta_description_en" => "",
    "meta_keywords_ru" => "",
    "meta_keywords_en" => ""
  },
  {
    "id" => 9,
    "title_ru" => "Пешком",
    "title_en" => "On foot",
    "description_ru" => "",
    "description_en" => "",
    "avatar" => "public/uploads/tour_type/avatar/9/hiking.jpg",
    "large_avatar" => "public/uploads/tour_type/large_avatar/9/peshkom.jpg",
    "slug_ru" => "",
    "slug_en" => "",
    "meta_title_ru" => "",
    "meta_title_en" => "",
    "meta_description_ru" => "",
    "meta_description_en" => "",
    "meta_keywords_ru" => "",
    "meta_keywords_en" => ""
  },
  {
    "id" => 11,
    "title_ru" => "Животные",
    "title_en" => "Animals",
    "description_ru" => "",
    "description_en" => "",
    "avatar" => "public/uploads/tour_type/avatar/11/dogsled.jpg",
    "large_avatar" => "public/uploads/tour_type/large_avatar/11/animals.jpg",
    "slug_ru" => "",
    "slug_en" => "",
    "meta_title_ru" => "",
    "meta_title_en" => "",
    "meta_description_ru" => "",
    "meta_description_en" => "",
    "meta_keywords_ru" => "",
    "meta_keywords_en" => ""
  },
  {
    "id" => 14,
    "title_ru" => "Вода",
    "title_en" => "Water",
    "description_ru" => "",
    "description_en" => "",
    "avatar" => "public/uploads/tour_type/avatar/14/surfing.jpg",
    "large_avatar" => "public/uploads/tour_type/large_avatar/14/water.jpg",
    "slug_ru" => "",
    "slug_en" => "",
    "meta_title_ru" => "",
    "meta_title_en" => "",
    "meta_description_ru" => "",
    "meta_description_en" => "",
    "meta_keywords_ru" => "",
    "meta_keywords_en" => ""
  },
  {
    "id" => 12,
    "title_ru" => "Мото",
    "title_en" => "Moto",
    "description_ru" => "",
    "description_en" => "",
    "avatar" => "public/uploads/tour_type/avatar/12/snowmobile.jpg",
    "large_avatar" => "public/uploads/tour_type/large_avatar/12/moto.jpg",
    "slug_ru" => "",
    "slug_en" => "",
    "meta_title_ru" => "",
    "meta_title_en" => "",
    "meta_description_ru" => "",
    "meta_description_en" => "",
    "meta_keywords_ru" => "",
    "meta_keywords_en" => ""
  }
]
TourType.create(tour_types) if TourType.count.zero?

tour_categories = [
  {
    "id" => 3,
    "title_ru" => "Йога",
    "title_en" => "Йога",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 9
  },
  {
    "id" => 4,
    "title_ru" => "Квест",
    "title_en" => "Квест",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 9
  },
  {
    "id" => 5,
    "title_ru" => "Экскурсия",
    "title_en" => "Экскурсия",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 9
  },
  {
    "id" => 6,
    "title_ru" => "Прогулка",
    "title_en" => "Прогулка",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 9
  },
  {
    "id" => 7,
    "title_ru" => "Скалолазание",
    "title_en" => "Скалолазание",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 9
  },
  {
    "id" => 8,
    "title_ru" => "Спуск по троллею",
    "title_en" => "Спуск по троллею",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 9
  },
  {
    "id" => 9,
    "title_ru" => "Треккинг",
    "title_en" => "Треккинг",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 9
  },
  {
    "id" => 10,
    "title_ru" => "Беговые лыжи",
    "title_en" => "Беговые лыжи",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 10
  },
  {
    "id" => 11,
    "title_ru" => "Горные лыжи",
    "title_en" => "Горные лыжи",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 10
  },
  {
    "id" => 12,
    "title_ru" => "Катание на санках",
    "title_en" => "Катание на санках",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 10
  },
  {
    "id" => 13,
    "title_ru" => "Коньки",
    "title_en" => "Коньки",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 10
  },
  {
    "id" => 14,
    "title_ru" => "Оленьи упряжки",
    "title_en" => "Оленьи упряжки",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 10
  },
  {
    "id" => 15,
    "title_ru" => "Снегоходы",
    "title_en" => "Снегоходы",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 10
  },
  {
    "id" => 16,
    "title_ru" => "Сноуборд",
    "title_en" => "Сноуборд",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 10
  },
  {
    "id" => 17,
    "title_ru" => "Собачьи упряжки",
    "title_en" => "Собачьи упряжки",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 10
  },
  {
    "id" => 18,
    "title_ru" => "Кони",
    "title_en" => "Кони",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 11
  },
  {
    "id" => 19,
    "title_ru" => "Оленьи упряжки",
    "title_en" => "Оленьи упряжки",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 11
  },
  {
    "id" => 20,
    "title_ru" => "Собачьи упряжки",
    "title_en" => "Собачьи упряжки",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 11
  },
  {
    "id" => 21,
    "title_ru" => "Автотур",
    "title_en" => "Автотур",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 12
  },
  {
    "id" => 22,
    "title_ru" => "Воздушная подушка",
    "title_en" => "Воздушная подушка",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 12
  },
  {
    "id" => 23,
    "title_ru" => "Катер",
    "title_en" => "Катер",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 12
  },
  {
    "id" => 24,
    "title_ru" => "Квадроциклы",
    "title_en" => "Квадроциклы",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 12
  },
  {
    "id" => 25,
    "title_ru" => "Круиз",
    "title_en" => "Круиз",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 12
  },
  {
    "id" => 26,
    "title_ru" => "Снегоходы",
    "title_en" => "Снегоходы",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 12
  },
  {
    "id" => 29,
    "title_ru" => "Дайвинг",
    "title_en" => "Дайвинг",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 14
  },
  {
    "id" => 30,
    "title_ru" => "Каньонинг",
    "title_en" => "Каньонинг",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 14
  },
  {
    "id" => 31,
    "title_ru" => "Катамараны",
    "title_en" => "Катамараны",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 14
  },
  {
    "id" => 32,
    "title_ru" => "Катер",
    "title_en" => "Катер",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 14
  },
  {
    "id" => 33,
    "title_ru" => "Круиз",
    "title_en" => "Круиз",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 14
  },
  {
    "id" => 34,
    "title_ru" => "Лодочная прогулка",
    "title_en" => "Лодочная прогулка",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 14
  },
  {
    "id" => 35,
    "title_ru" => "Моркские каяки",
    "title_en" => "Моркские каяки",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 14
  },
  {
    "id" => 36,
    "title_ru" => "Рафты",
    "title_en" => "Рафты",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 14
  },
  {
    "id" => 37,
    "title_ru" => "Рыбалка",
    "title_en" => "Рыбалка",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 14
  },
  {
    "id" => 38,
    "title_ru" => "Серфинг",
    "title_en" => "Серфинг",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 14
  },
  {
    "id" => 39,
    "title_ru" => "Снорклинг",
    "title_en" => "Снорклинг",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 14
  },
  {
    "id" => 40,
    "title_ru" => "Сплав",
    "title_en" => "Сплав",
    "description_ru" => '',
    "description_en" => '',
    "slug_ru" => '',
    "slug_en" => '',
    "meta_title_ru" => '',
    "meta_title_en" => '',
    "meta_description_ru" => '',
    "meta_description_en" => '',
    "meta_keywords_ru" => '',
    "meta_keywords_en" => '',
    "tour_type_id" => 14
  },
  {
    "id" => 1,
    "title_ru" => "Виа-Феррата",
    "title_en" => "Виа-Феррата",
    "description_ru" => "",
    "description_en" => "",
    "slug_ru" => "",
    "slug_en" => "",
    "meta_title_ru" => "",
    "meta_title_en" => "",
    "meta_description_ru" => "",
    "meta_description_en" => "",
    "meta_keywords_ru" => "",
    "meta_keywords_en" => "",
    "tour_type_id" => 9
  },
  {
    "id" => 2,
    "title_ru" => "Восхождение",
    "title_en" => "Восхождение",
    "description_ru" => "",
    "description_en" => "",
    "slug_ru" => "",
    "slug_en" => "",
    "meta_title_ru" => "",
    "meta_title_en" => "",
    "meta_description_ru" => "",
    "meta_description_en" => "",
    "meta_keywords_ru" => "",
    "meta_keywords_en" => "",
    "tour_type_id" => 9
  },
  {
    "id" => 28,
    "title_ru" => "Байдарки",
    "title_en" => "Kayak",
    "description_ru" => "",
    "description_en" => "",
    "slug_ru" => "байдарки",
    "slug_en" => "kayak",
    "meta_title_ru" => "",
    "meta_title_en" => "",
    "meta_description_ru" => "",
    "meta_description_en" => "",
    "meta_keywords_ru" => "",
    "meta_keywords_en" => "",
    "tour_type_id" => 14
  },
  {
    "id" => 41,
    "title_ru" => "Яхта",
    "title_en" => "Яхта",
    "description_ru" => "",
    "description_en" => "",
    "slug_ru" => "",
    "slug_en" => "",
    "meta_title_ru" => "",
    "meta_title_en" => "",
    "meta_description_ru" => "",
    "meta_description_en" => "",
    "meta_keywords_ru" => "",
    "meta_keywords_en" => "",
    "tour_type_id" => 14
  },
  {
    "id" => 27,
    "title_ru" => "Велотур",
    "title_en" => "Велотур2",
    "description_ru" => "5",
    "description_en" => "6",
    "slug_ru" => "3",
    "slug_en" => "4",
    "meta_title_ru" => "7",
    "meta_title_en" => "8",
    "meta_description_ru" => "9",
    "meta_description_en" => "10",
    "meta_keywords_ru" => "11",
    "meta_keywords_en" => "12",
    "tour_type_id" => 12
  }
]
TourCategory.create(tour_categories) if TourCategory.count.zero?

pages = JSON.parse(File.read("#{Rails.root}/db/seeds/pages.json"))
Page.create(pages) if Page.count.zero?